In [ ]:
import numpy as np

def m_init(shape,value=0):
    """
    this function create a matrix of any value 
    """
    
    return np.full(shape,value)

m_init((3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
import pandas as pd
s = pd.Series([1,2,3,4,5,6],index = ["A","B","C","D","E","F"])
s

A    1
B    2
C    3
D    4
E    5
F    6
dtype: int64

In [15]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]

# data = {'col1':[1,2,3,4],
#         'col2':[444,555,666,444],
#         'col3':['abc','def','ghi','xyz']}

df = pd.DataFrame(data,columns=['col1','col2','col3'])
display(df)
df.columns=['id','salary','dep']
df.dtypes

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

id        int64
salary    int64
dep         str
dtype: object

In [14]:
df.dep.dtype

In [17]:
df['dep']=df['dep'].astype('category')
df.dtypes

id           int64
salary       int64
dep       category
dtype: object

In [18]:
cols_cat = ["id","salary"]
df[cols_cat]=df[cols_cat].astype('category')
df.dtypes

id        category
salary    category
dep       category
dtype: object

In [23]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]

df = pd.DataFrame(data,columns=['col1','col2','col3'])

df.head()
df.tail()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [24]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='str')

In [25]:
df['col2'].unique()

array([444, 555, 666])

In [26]:
classification = df['col2'].unique()
classification

array([444, 555, 666])

In [28]:

def get_range(df):
    
    return df.max() - df.min()

get_range(df.col1)

np.int64(3)

In [29]:
df.col2.value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      str
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [31]:
df.col2.values

array([444, 555, 666, 444])

In [32]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 444, 'xyz']], dtype=object)

In [33]:
df.replace(555,"abanob")

   col1    col2 col3
0     1     444  abc
1     2  abanob  def
2     3     666  ghi
3     4     444  xyz